services:
  - type: web
    name: train-ticket
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: train-ticket-db
          property: connectionString

databases:
  - name: train-ticket-db
    databaseName: train_ticket
    user: train_ticket
